# Generated by Django 5.1.7 on 2025-04-30 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('faulty', 'Faulty'), ('out_of_service', 'Out of Service')], default='operational', max_length=20)),
                ('etat', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=50)),
                ('date_installation', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Unknown', max_length=200)),
                ('capacite', models.IntegerField(default=0)),
                ('date_installation', models.DateField(default=django.utils.timezone.now)),
                ('localisation', models.CharField(default='Non spécifiée', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.sensor')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='station.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='station.station'),
        ),
    ]
