# Generated by Django 5.1.7 on 2025-05-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_desalinationstation_alert_stationparameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='stationparameters',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='stationparameters',
            name='salinity',
        ),
        migrations.RemoveField(
            model_name='stationparameters',
            name='temperature',
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stationparameters',
            name='parameter_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stationparameters',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.desalinationstation'),
        ),
        migrations.AlterField(
            model_name='stationparameters',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.desalinationstation'),
        ),
    ]
